### ISSUE TITLE
Quick picks based on last song played

### ISSUE THREAD

**Issue by siggi1984** [DanielSevillano/music-you#1]
Most of the time, the quick picks are not based on the last song played. It would be better if the quick picks were based on the last song played.

Even better would be a selection option like Harmony Music, see screenshot.
I think the quick picks are very successful.

![295985709-ee4eeb19-1a2b-4062-95b6-4b0a41918073](https://github.com/DanielSevillano/music-you/assets/103368536/8d657d2f-e6bb-40ef-ae43-99f29fd64d7d)

**Comment by DanielSevillano** [comment]
Thanks for the suggestion! I like the idea, I'll look into it.

**Comment by DanielSevillano** [comment]
Implemented!

**Comment by siggi1984** [comment]
> Implemented!

Thanks
