### ISSUE TITLE
[Bug] app is crashing on startup 

### ISSUE THREAD

**Issue by srt54558** [DanielSevillano/music-you#13]
Hello,
I installed the newest version and the app doesn't even open. It instantly crashes on startup.

Android 14 QPR 2/ March Update/ stable

Google pixel 8 Pro
Rooted

**Comment by DanielSevillano** [comment]
Thank you for reporting this bug. Can you provide the logs?

**Comment by srt54558** [comment]
> Thank you for reporting this bug. Can you provide the logs?

After a reinstall it worked fine again. I don't know why

**Comment by DanielSevillano** [comment]
> After a reinstall it worked fine again. I don't know why

I'm glad it works now! 😄
