### ISSUE TITLE
Swipe to change the title in the minimized player

### ISSUE THREAD

**Issue by siggi1984** [DanielSevillano/music-you#16]
Swipe to the left in the minimized player to go to the next track, swipe to the right to go to the previous track.
See screenshot.
![Screenshot_20240313-191808_Music You_1](https://github.com/DanielSevillano/music-you/assets/103368536/f095a874-c30c-441b-b09d-18f2dec24ec6)

**Comment by DanielSevillano** [comment]
Great idea! I have already implemented it, a new version will be available soon with this feature.
