### ISSUE TITLE
Swipe to delete a song

### ISSUE THREAD

**Issue by siggi1984** [DanielSevillano/music-you#17]
Swipe to the left to delete a song from the playlists, at the same time as a message is displayed for a few seconds to undo the action (if you have swiped by mistake).

![Screenshot_20240321-090415_Music You](https://github.com/DanielSevillano/music-you/assets/103368536/b3395931-e8f1-4d39-a9b4-ca1c7fe03841)

**Comment by DanielSevillano** [comment]
I will implement this feature soon, thanks for the idea!

**Comment by DanielSevillano** [comment]
I have implemented swipe to delete in playlists and queue, although without an undo message. Please let me know if it works as expected and if you think that the undo feature is necessary.

**Comment by siggi1984** [comment]
> I have implemented swipe to delete in playlists and queue, although without an undo message. Please let me know if it works as expected and if you think that the undo feature is necessary.

Swiping to delete works well in the queue and playlists, thank you. I think this function should also be implemented in the song area and the undo option is definitely missing if you swipe by mistake.

**Comment by DanielSevillano** [comment]
You're right, I would be a great improvement. I'll try to implement the undo option in the future.

**Comment by yonoff** [comment]
Also, on the “Playing Now” screen, when you swipe from the edge of the screen to go back, the track often switches to the next or previous one. I think you need to reduce the sensitivity of the gestures so that they do not conflict with Android's navigation gestures.

**Comment by DanielSevillano** [comment]
> Can you make this "Swipe to delete song" feature optional. IMHO, not everyone likes this feature. This often happens accidentally.

That's a good point. I could add gesture settings and allow the user to decide which ones to disable.

> Also, on the “Now Playing” screen, when I swipe from the edge of the screen to go back, the track often switches to the next or previous one. I think you need to reduce the sensitivity of the gestures so that they do not conflict with Android's navigation gestures.

That's true, I want to rework that gesture and the one to close the mini player.

**Comment by DanielSevillano** [comment]
> The undo option is definitely missing if you swipe by mistake.

I've added snackbars to undo swipe actions, I hope it works as expected!
