### ISSUE TITLE
Full screen lyrics

### ISSUE THREAD

**Issue by siggi1984** [DanielSevillano/music-you#20]
Displaying the lyrics in full screen would be cool. With an icon at the bottom left of the song cover (as with RiMusic) or by zooming the lyrics when they are already displayed (as with ViTune) or a completely new idea.

**Comment by DanielSevillano** [comment]
That's a great idea! I'll think about the implementation, thanks.

**Comment by DanielSevillano** [comment]
It has been implemented, it will be available in the next version.
