### ISSUE TITLE
Automatic change to the artist

### ISSUE THREAD

**Issue by siggi1984** [DanielSevillano/music-you#21]
If you want to switch to the artist page, this happens in the background at the moment (see video) you have to minimize the player to see the artist page. I would find it better if the change took place automatically.

https://github.com/DanielSevillano/music-you/assets/103368536/eb886557-6e25-4d2c-b6c5-1fe317ead866

**Comment by DanielSevillano** [comment]
This is already fixed, it will be available in the next version 🥳
