### ISSUE TITLE
app crashing when open

### ISSUE THREAD

**Issue by BlackSparkz** [DanielSevillano/music-you#23]
Here a vdo
Samsung galaxy a34 android 14 oneui 6

https://github.com/DanielSevillano/music-you/assets/78287172/82753b21-432f-4d1e-b7b2-0ae799bcad80

**Comment by DanielSevillano** [comment]
It seems to be the same bug reported in #18, which affects devices with Android 14. It will be fixed in the next release, sorry for the inconvenience.

**Comment by DanielSevillano** [comment]
Hi! Could you please confirm if the app works with the latest version?
