### ISSUE TITLE
Search function in the song area

### ISSUE THREAD

**Issue by siggi1984** [DanielSevillano/music-you#24]
A search function in the song area would be cool, then you would have to scroll forever when looking for a specific song to delete it, for example ...

**Comment by DanielSevillano** [comment]
That's a great idea, it would really useful to users with lots of songs in their library. I'll think about how to implement it. I hope to have some free time soon.

**Comment by DanielSevillano** [comment]
Implemented! There's now a new option to search in your library.

<img src="https://github.com/DanielSevillano/music-you/assets/68847306/1eb280e5-b73a-4188-8eb5-7771cbaec437" width="200px">
