### ISSUE TITLE
insant crash when i run it

### ISSUE THREAD

**Issue by malsvn** [DanielSevillano/music-you#25]
title

**Comment by DanielSevillano** [comment]
Hi! Are you running Android 14?

**Comment by DanielSevillano** [comment]
It's probably the same bug reported in #18. It will be fixed in the next release, I hope to release it soon.

**Comment by DanielSevillano** [comment]
I have just released a new version with the fix. Could you please confirm if the app works now in your device?

**Comment by DanielSevillano** [comment]
Thanks, that's great! 🥳
