### ISSUE TITLE
[Enhancement]: Play Age-restricted Music

### ISSUE THREAD

**Issue by DarkCrypt** [DanielSevillano/music-you#27]
Add support to play age-restricted music.

**Comment by DanielSevillano** [comment]
I didn't know that it wasn't possible, thanks for opening the issue. I'll look into it.

**Comment by DanielSevillano** [comment]
I have changed the Piped instance to bypass age restriction, it should be possible to play age-restricted music now.

**Comment by DarkCrypt** [comment]
Awesome! I can confirm this issue is fixed. Thank you!
