### ISSUE TITLE
Skip song if not found

### ISSUE THREAD

**Issue by siggi1984** [DanielSevillano/music-you#29]
With these errors

-An unknown playback error occurred
– The requested video ID was not found

the music stops.

It would be good if, in the event of these errors, the player would automatically jump to the next song in the queue, with a simultaneous notification as to which song was skipped. To possibly delete the song to keep his library clean.

**Comment by DanielSevillano** [comment]
Skipping songs when the ID isn't found would be a great improvement, I'll try to implement it in the future.

I'm not sure if jumping to the next song when an unknown error occurs is the best option, because the playback can be resumed by clicking on the cover.
