### ISSUE TITLE
Can add this options for player appearance ?

### ISSUE THREAD

**Issue by chamudha** [DanielSevillano/music-you#32]
![Picsart_24-06-22_10-30-02-799.jpg](https://github.com/DanielSevillano/music-you/assets/134184550/179f1088-0785-49bf-aa84-030f98d3d9da)

**Comment by DanielSevillano** [comment]
You mean something like [this](https://firebasestorage.googleapis.com/v0/b/design-spec/o/projects%2Fm3%2Fimages%2Fkykifyox-multiple-transitions3P.mp4?alt=media)?

**Comment by chamudha** [comment]
> You mean something like [this](https://firebasestorage.googleapis.com/v0/b/design-spec/o/projects%2Fm3%2Fimages%2Fkykifyox-multiple-transitions3P.mp4?alt=media)?

Ya,like it.

**Comment by DanielSevillano** [comment]
New themes are not planned for now. I don't know if adding the ability to change the default tab is really necessary, the app already remembers the last tab opened.
