### ISSUE TITLE
Please implement 'right swipe to play next' 

### ISSUE THREAD

**Issue by siggi1984** [DanielSevillano/music-you#33]
https://github.com/DanielSevillano/music-you/assets/103368536/624d63ae-f07f-4425-8ba8-737dea62ca22

**Comment by DanielSevillano** [comment]
Great idea! Although I think that it should trigger add to queue, instead of play next.

Anyway, where should this gesture be available? In albums and search it would interfere with tabs.

**Comment by siggi1984** [comment]
> Great idea! Although I think that it should trigger add to queue, instead of play next.
> 
> Anyway, where should this gesture be available? In albums and search it would interfere with tabs.

So actually it would be cool if this gesture was available everywhere possible (otherwise where it does not negatively affect the APP stability and function)

**Comment by DanielSevillano** [comment]
I've implemented swipe to enqueue everywhere except in albums and artists, because of the tabs.

**Comment by DanielSevillano** [comment]
Swipe to enqueue is available in the latest release.
