### ISSUE TITLE
Search bar not working

### ISSUE THREAD

**Issue by Capodoglio90** [DanielSevillano/music-you#38]
I've just updated to the new version. When I search for a song, it basically doesn't search for the song. It keeps showing me the search bar and the suggestions.

(Android version: 8.1.0)

https://github.com/user-attachments/assets/e38bed47-4932-469e-aaa5-1be85c508f3d

**Comment by DanielSevillano** [comment]
I don't know what's causing the issue, I'll try to investigate.

**Comment by Capodoglio90** [comment]
Thanks, it actually saves the search but, as you can see, it doesn't show the results.

**Comment by Capodoglio90** [comment]
Yes, it works, thank you so much.

**Comment by DanielSevillano** [comment]
Great! 🥳 It will be widely available in the next version. Thanks for reporting the issue.
