### ISSUE TITLE
Add link to artist page and album

### ISSUE THREAD

**Issue by siggi1984** [DanielSevillano/music-you#5]
Clicking on the name of the artist in the song player should take you to the artist's page. Clicking on the title should take you to the album. Without the current detours.

![Screenshot_20240226-195801_Music You](https://github.com/DanielSevillano/music-you/assets/103368536/6122a4ec-18c1-41d8-9cc2-5055041f8817)

**Comment by DanielSevillano** [comment]
I like the idea, it would make navigating easier. I want to rework a few things in the player first, though.

**Comment by siggi1984** [comment]
> I like the idea, it would make navigating easier. I want to rework a few things in the player first, though.

All good, one thing at a time, take the time you need.

**Comment by DanielSevillano** [comment]
I have partially implemented this feature in version 0.4. The artists name is now clickable if the song has only one of them. I don't think that approach works with multiple artists, though. On the other hand, I think that opening the album by clicking on the song title isn't intuitive enough, at least with the current layout. Let me know what you think.

**Comment by siggi1984** [comment]
> I have partially implemented this feature in version 0.4. The artists name is now clickable if the song has only one of them. I don't think that approach works with multiple artists, though. On the other hand, I think that opening the album by clicking on the song title isn't intuitive enough, at least with the current layout. Let me know what you think.

Clicking on the artist name doesn't work for any song???

**Comment by DanielSevillano** [comment]
> Clicking on the artist name doesn't work for any song???

It should work for songs with only one artist.

**Comment by siggi1984** [comment]
> > Clicking on the artist name doesn't work for any song???
> 
> It should work for songs with only one artist.

Unfortunately, it doesn't work for any song, not even for songs with only one artist.

**Comment by DanielSevillano** [comment]
That's strange, it works on my device. Could you try to clear the app data? Sorry for the inconvenience.

**Comment by siggi1984** [comment]
> That's strange, it works on my device. Could you try to clear the app data? Sorry for the inconvenience.

If I delete the APP data then it works, but when I restore my data it doesn't work again.

**Comment by DanielSevillano** [comment]
It seems that it only works with songs that aren't in the library. Thanks for helping me identify the issue, I'll look into it.

**Comment by DanielSevillano** [comment]
Okay, it should work now for every song with one artist 😅

**Comment by siggi1984** [comment]
It works for songs with one artist, maybe in the future they'll get it to work for songs with multiple artists because it works.

**Comment by siggi1984** [comment]
> Okay, it should work now for every song with one artist 😅

It works for songs with one artist, maybe in the future they'll get it to work for songs with multiple artists because it works.
